name: Dockerize-app-test
env:
  APPLICATION_NAME : "test2"

on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Bulding and pushing Docker image with application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo ${{ env.APPLICATION_NAME }}
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.APPLICATION_NAME }}:latest, ${{ secrets.DOCKER_USERNAME }}/${{ env.APPLICATION_NAME }}:${{ github.run_number }}
          
