name: Dockerize-app-test2

on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Bulding and pushing Docker image with app-test2 application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo test2
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tozteritta/test2:latest, tozteritta/test2:${{ github.run_number }}
          
