name: Dockerize-test-app

on:
  push:
    branches:
      - main

jobs:
  build-container:
    name: Buld Docker container test app image from file
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo test2
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and pusg
        uses: docker/build-push-action@v2
        with:
          #context: .
          push: true
          tags: tozteritta/test2:latest, tozteritta/test2:${{ github.run_number }} 
                
      
