name: Dockerize-test-app

on:
  push:
    branches:
      - main

jobs:
  build-container:
    name: Buld Docker container test app image from file
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo test2
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tozteritta/test2
          tags: latest          
